# Oinarrizko zerbitzari konfigurazioa
port 1194
# OpenVPN entzuten egongo den portu zenbakia, defektuz 1194
proto tcp-server
# Protokoloa, UDP edo TCP
tls-server
# TLS aktibatu eta zerbitzari eginkizunak aurrera eraman TLS handshake gara>
# Aukerako ezarpenak
tun-mtu 1400
# Pakete bakoitzaren tamaina maximoa bytetan
keepalive 60 300
# Konexioa bizirik dagoela edo eten dela ziurtatzeko tartea
# Sare ezarpenak
dev ovpn
# Sareko interfazearen izena
dev-type tun
# Sareko interfaze mota, TAP edo TUN
server 10.8.0.0 255.255.255.0
# VPN bezeroen sare birtualeko helbide eta maskara
topology subnet
# Sare birtualaren topologia mota, subnet, net30 edo p2p
route 10.88.10.0 255.255.255.248
client-config-dir /etc/openvpn/ccd

# Zerbitzariak partekatzen duen sare helbide eta maskara
# Gako eta zertifikatuak
dh none
# Diffie-Hellman parametroak, none bada kanal ez seguru bat erabiliz partek># ezartzeko Elliptic Curve Diffie-Hellman protokoloa erabiltzen da
cert /etc/openvpn/server/zertifikatua.crt
# Zerbitzariaren zertifikatua
key /etc/openvpn/server/gakoa.key
# Zerbitzariaren gakoa
<peer-fingerprint>
# Bezeroaren edo bezeroen fingerprinting-ak
AE:3B:39:64:5F:F1:D9:7F:09:B5:45:E3:58:13:3B:2E:98:08:E7:3B:A4:D4:67:76:9A:B2:E7:76:D0:C8:78:0E
</peer-fingerprint>

