# Oinarrizko bezero konfigurazioa
port 1194
# OpenVPN zerbitzaria entzuten egongo den portu zenbakia, defektuz 1194
proto tcp-client
# Protokoloa, UDP edo TCP
tls-client
# TLS aktibatu eta bezero eginkizunak aurrera eraman TLS handshake garaian
# Aukerako ezarpenak
tun-mtu 1400
# Pakete bakoitzaren tamaina maximoa bytetan
keepalive 60 300
# Konexioa bizirik dagoela edo eten dela ziurtatzeko tartea
# Sare ezarpenak
dev ovpn
# Sareko interfazearen izena
dev-type tun
# Sareko interfaze mota, TAP edo TUN
pull
# VPN zerbitzariak bidalitako aukerak ezarri
# Gako eta zertifikatuak
cert /etc/openvpn/client/zertifikatua.crt
# Zerbitzariaren zertifikatua
key /etc/openvpn/client/gakoa.key
# Zerbitzariaren gakoa
<peer-fingerprint>
# Zerbitzariaren fingerprinting-a
A2:4D:85:D0:5D:3F:0F:C6:4D:CD:AF:2C:B3:60:7B:E5:3F:3E:9C:4A:77:49:AB:C3:41:63:48:96:E4:A7:71:54
</peer-fingerprint>
